//у пользователя director массив включает в себя модули на которые нет доступа
//у остальных пользователей массив включает в себя модули на которые есть доступ
const rules = {
  admin: {
    static: [
      "point",
      "stock",
      "cashbox",
      "cashboxuser",
      "general",
      "uploadfile",
      "stats",
      "product",
      "promotionspage",
      "news",
    ],
  },
  director: {
    static: ["revision", "reportholdingpage"],
  },
  aladin: {
    static: ["*"],
  },
  accountant: {
    static: [
      "report",
      "reportCashboxState",
      "reportSalesSection",
      "reportTransactions",
      "reportSales",
      "reportSalesPlan",
      "reportSalesPlanTeam",
      "reportFizCustomers",
      "reportDiscounts",
      "reportIncome",
      "reportStockBalance",
      "reportInvoiceHistory",
      "reportProductMovement",
      "reportRevision",
      "general",
      "counterparties",
      "esf",
      "buyers",
      "options",
      "stats",
      "product",
      "creatediscounts",
      "bonus",
      "promotionspage",
      "certificates",
      "news",
      "pricingmaster",
    ],
  },
  supplier: {
    static: [
      "report",
      "reportStockBalance",
      "reportInvoiceHistory",
      "reportProductMovement",
      "reportRevision",
      "product",
      "receive",
      "transfer",
      "addcategory",
      "changeprice",
      "writeoff",
      "addbrand",
      "general",
      "printbarcode",
      "counterparties",
      "options",
      "marginalprice",
      "promotionspage",
      "certificates",
      "news",
      "productsweight",
    ],
  },
  pointHead: {
    static: [
      "report",
      "reportCashboxState",
      "reportSalesSection",
      "reportTransactions",
      "reportSales",
      "reportSalesPlan",
      "reportSalesPlanTeam",
      "reportFizCustomers",
      "reportDiscounts",
      "reportIncome",
      "reportStockBalance",
      "reportInvoiceHistory",
      "reportProductMovement",
      "reportRevision",
      "point",
      "options",
      "stock",
      "cashbox",
      "cashboxuser",
      "general",
      "stockreport",
      "report",
      "stats",
      "product",
      "creatediscounts",
      "bonus",
      "promotionspage",
      "news",
      "pricingmaster",
    ],
  },
  undefined: {
    static: [],
  },

  revisor: {
    static: ["revision", "product", "news"],
  },
  holder: {
    static: ["report", "reportholdingpage", "news"],
  },
};

export default rules;
