//у пользователя director массив включает в себя модули на которые нет доступа
//у остальных пользователей массив включает в себя модули на которые есть доступ
const rules = {
  admin: {
    static: [
      "options",
      "erpuser",
      "point",
      "stock",
      "cashbox",
      "cashboxuser",
      "general",
      "uploadfile",
      "stats",
      "product",
      "promotionspage",
      "createnews",
      "news",
    ],
  },
  director: {
    static: ["revision"],
  },
  aladin: {
    static: ["*"],
  },
  accountant: {
    static: [
      "options",
      "erpuser",
      "stockreport",
      "report",
      "general",
      "counterparties",
      "esf",
      "buyers",
      "references",
      "stats",
      "marketing",
      "couponspage",
      "creatediscounts",
      "bonus",
      "promotionspage",
      "certificates",
      "news",
      "pricingmaster",
    ],
  },
  supplier: {
    static: [
      "options",
      "erpuser",
      "stockreport",
      "certificates",
      "product",
      "receive",
      "transfer",
      "categories",
      "attrspr",
      "brand",
      "addcategory",
      "writeoff",
      "addbrand",
      "general",
      "printbarcode",
      "counterparties",
      "references",
      "prices",
      "marginalpricepage",
      "changeprice",
      "pricingmaster",
      "options",
      "promotionspage",
      "news",
      "productsweight",
      "productreference",
    ],
  },
  pointHead: {
    static: [
      "options",
      "erpuser",
      "point",
      "references",
      "stock",
      "cashbox",
      "cashboxuser",
      "general",
      "stockreport",
      "report",
      "stats",
      "product",
      "news",
      "pricingmaster",
      "prices",
      "marginalpricepage",
      "changeprice"
    ],
  },
  catman: {
    static: [
      "options",
      "erpuser",
      "report",
      "stockreport",
      "prices",
      "marginalpricepage",
      "changeprice",
      "pricingmaster",
      "product",
      "createworkorder",
      "acceptworkorder",
      "recievebyworkorder"
    ]
  },
  undefined: {
    static: [],
  },
  revisor: {
    static: [
      "revision", 
      "product", 
      "news", 
    ],
  },
};

export default rules;
